services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USER: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build:
      # context: ./backend
      # dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes: 
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    # build:
      # context: ./frontend
      # dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    # env_file:
    #   - ./env/frontend.env
    depends_on:
      - backend

volumes:
  data:
  logs:
