apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # This will create a service that is only accessible from within the cluster but not from outside
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80