apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  # This will create a service that is only accessible from within the cluster but not from outside
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80